version: '3.7'

services:
  poke-redis:
    image: redis
    container_name: poke-redis
    restart: unless-stopped
    networks:
      - pokenet
    ports:
      - 6379:6379
  poke-db:
    image: postgres
    container_name: poke-postgres
    restart: unless-stopped
    volumes:
      - /opt/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=battle_log_db
    networks:
      - pokenet
  poke-django:
    build: .
    container_name: poke
    restart: unless-stopped
    command: bash /usr/src/pokeservice/startup_script.sh
    volumes:
      - .:/usr/src/pokeservice
    ports:
      - 8000:8000
    depends_on:
      - poke-db
      - poke-redis
    networks:
      - pokenet
      - internet
    environment:
      - DJANGO_SMTP_EMAIL=your@mail.ru
      - DJANGO_SMTP_EMAIL_PASSWORD=yourpassword
networks:
  internet:
    name: internet
    driver: bridge
  pokenet:
    name: pokenet
    driver: bridge