# Generated by Django 4.2.7 on 2023-11-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_date', models.DateTimeField()),
                ('battle_round', models.IntegerField()),
                ('user_pokemon', models.CharField(max_length=30)),
                ('enemy_pokemon', models.CharField(max_length=30)),
                ('battle_round_winner', models.CharField(max_length=30)),
            ],
        ),
    ]
