# Generated by Django 4.2.7 on 2023-12-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pokemon'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_pokemon_id', models.IntegerField()),
                ('second_pokemon_id', models.IntegerField()),
                ('first_pokemon_hp', models.IntegerField()),
                ('second_pokemon_hp', models.IntegerField()),
                ('first_pokemon_roll', models.IntegerField()),
                ('second_pokemon_roll', models.IntegerField()),
                ('round_number', models.IntegerField()),
                ('winner_id', models.IntegerField()),
                ('is_last', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Pokemon',
        ),
    ]
